### ISSUE TITLE
Can't locate version.pm

### ISSUE THREAD

**Issue by daominh6879** [jandrew/Spreadsheet-XLSX-Reader-LibXML#101]
Hi There,

This is the first time I'm using this script and I encountered with a problem "Can't locate version.pm".
Can you give me any hint about it?
Thanks a lot!

**Comment by jandrew** [comment]
@daominh6879 

First I need to let you know that this package is [depricated](https://github.com/jandrew/Spreadsheet-XLSX-Reader-LibXML#deprecation) in favor of [Spreadsheet::Reader::ExcelXML](https://metacpan.org/pod/Spreadsheet::Reader::ExcelXML) although I would expect you to have the same issues with version.pm for that package as for this one.

[version.pm](https://metacpan.org/pod/distribution/version/lib/version.pod) should be core for perls 5.10 and newer but you can [add it to your system from CPAN](http://www.cpan.org/modules/INSTALL.html).  However, this package is unlikely to work for perls earlier that 5.10 for other reasons as well.  You can test what version of perl you are using with the line;

  perl -v

Best Regards,

Jed

**Comment by daominh6879** [comment]
Hi Jed,

Thanks a lot for help. I can use this script now

Best,
Hung
