### ISSUE TITLE
LibXML.pm line 671 skips 'worksheet', next line processes it

### ISSUE THREAD

**Issue by Frank071** [jandrew/Spreadsheet-XLSX-Reader-LibXML#27]
LibXML.pm contains a conditional next on line 671 that fires when the object is a worksheet. Yet the next (non comment) line is an if that should fire to process exactly that type of object. If this is not an error, then a clarifying comment would do a world of good :-)

**Comment by jandrew** [comment]
Sorry for the delay in response.  Let me look this over and I will get back with you by this evening.

**Comment by jandrew** [comment]
So after some review this 'if' section is a piece of older cruft in the code.  I used to set the SuperClass for the worksheet here based on the interpreter type but now I just reference the variable $parser_modules (line 35) directly.  Commenting out lines 671 - 678 and 717 - 719.  The package still passes all tests.  I'll remove those lines in the next release
