### ISSUE TITLE
Empty shared string crashes SharedStrings.pm

### ISSUE THREAD

**Issue by wdbaker54** [jandrew/Spreadsheet-XLSX-Reader-LibXML#40]
I am by no means someone who groks the rules of xml formatting but while parsing an xlsx file the SharedStrings.pm failed on line 85 while parsing:

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="485" uniqueCount="327">
    <si>
        <t />
    </si>`

I was able to get it to pass by wrapping lines 85 and 86 in a "if ( is_HashRef $element ) {}" and it appeared to correctly finish parsing my xlsx file.

**Comment by jandrew** [comment]
Bill,  Thanks for pointing this out.  Do you have an .xlsx file you could share that fails for this error?  It would help.  I would also like to have permission to include it in the test suite but I understand if you don't want it published with the module.

**Comment by jandrew** [comment]
With apologies I have a second question.  I'm currently working on a largish re-write of the guts to support the Microsoft XML 2003 spredsheet specification as well (milestone v0.38.2 - I will probably roll this fix as v0.36.20) and I am wondering if I just push this fix to github will that be sufficient for you or are you looking to get a push all the way to CPAN?

**Comment by wdbaker54** [comment]
Sorry it took so long to get back with you but the spreadsheets we are using comes from our clients and contains sensitive information. I was hoping that editing the spreadsheet using either Open Office or Excel to remove the sensitive parts and sending that version to you but it seems to also remove the problem. It's almost as if the files are self-healing :)

**Comment by jandrew** [comment]
Bill,  No problem the snippet you gave me is enough for a test case but I generally don't see empty shared strings files so I was hoping to get some background.  You are correct in observing that .xlsx files can be self healing (especially through the magic of Microsoft) but that doesn't mean I won't protect against edge cases.  Give me a couple of days and I'll post an update.

**Comment by jandrew** [comment]
Bill,  In the end my first two attempts didn't pass test (well actually the first attempt had a bad test) so I rolled the number for the fix all the way to v0.36.24.  I just pushed it all the way to CPAN so you should see it soon.

**Comment by wdbaker54** [comment]
Thanks for the work on this - I have installed the update and everything appears to be running smoothly.

**Comment by jandrew** [comment]
Bill,  No problem.  The goal of this package has always been to catch the corner cases.  Your report just helped the package be that more robust.
