### ISSUE TITLE
Crash in SharedStrings

### ISSUE THREAD

**Issue by Tux** [jandrew/Spreadsheet-XLSX-Reader-LibXML#49]
Using a simple xlsx testfile I also use in my Spreadsheet::Read tests:
https://github.com/Tux/Spreadsheet-Read/blob/master/files/values.xlsx

$ perl -MSpreadsheet::XLSX::Reader::LibX
ML -e'my$wb=Spreadsheet::XLSX::Reader::LibXML->new->parse("files/values.xlsx");f
or$s($wb->worksheets){@cr=$s->col_range;@rr=$s->row_range;for$r($rr[0]..$rr[1]){
for$c($cr[0]..$cr[1]){$cell=$s->get_cell($r,$c);}}}'
Can't use string ("t") as a HASH ref while "strict refs" in use at /pro/lib/perl5/site_perl/5.22.0/Spreadsheet/XLSX/Reader/LibXML/XMLReader/SharedStrings.pm line 254.

**Comment by jandrew** [comment]
Tux, Thanks for submitting this.  I will look at it today.

**Comment by jandrew** [comment]
OK,  I have confirmed the error on my side as well and I have a formal test case now.  Based on my availability I don't expect to get to this till the weekend.

**Comment by jandrew** [comment]
OK,  So I got caught up in my move to Portland and basically dropped this work but I should be able to commit some time to it now.
