### ISSUE TITLE
Cannot parse legal XLSX file

### ISSUE THREAD

**Issue by Tux** [jandrew/Spreadsheet-XLSX-Reader-LibXML#51]
$ mkdir files
$ wget https://github.com/Tux/Spreadsheet-Read/blob/master/files/perc.xlsx -O files/perc.xlsx
$ perl -MSpreadsheet::XLSX::Reader::LibX
ML -wE'my$p=Spreadsheet::XLSX::Reader::LibXML->new;$p->parse("files/perc.xlsx")o
r die$p->error'
Can't call method "extractToFileHandle" on an undefined value at /pro/lib/perl5/site_perl/5.22.0/Spreadsheet/XLSX/Reader/LibXML.pm line 693.

**Comment by jandrew** [comment]
@Tux,  I will check into this today too

**Comment by jandrew** [comment]
OK,  I also have a test case for this one now.  Thanks for the code.  I look to have this done by the weekend
