### ISSUE TITLE
No information available about hidden cells (or rows or columns)

### ISSUE THREAD

**Issue by Tux** [jandrew/Spreadsheet-XLSX-Reader-LibXML#53]
$cell->is_hidden would do

Note that Spreadsheet::Parse{Excel,XLSX} hold both hidden and merged info in the Fmt object

**Comment by jandrew** [comment]
This is also one of the future method matching issues pending.  For now I will assign it to milestone v0.38.10 but I don't yet have a solid test case and it may need to be pulled from pretty deep in the XML.  If so I reserve the right to bump it to v0.40.2 milestone.

**Comment by jandrew** [comment]
This is ready now too but I will wait and priority fix #65 first.

**Comment by jandrew** [comment]
As far as I can tell this was closed by pull request #66
