### ISSUE TITLE
consider using a different version system

### ISSUE THREAD

**Issue by Tux** [jandrew/Spreadsheet-XLSX-Reader-LibXML#71]
```
$ perl -MSpreadsheet::XLSX::Reader::LibXML=v0.38.2 -e1
Passed attribute default flag -v0.38.2- does not comply with the correct format at /pro/lib/perl5/site_perl/5.22.0/Spreadsheet/XLSX/Reader/LibXML.pm line 261.
        Spreadsheet::XLSX::Reader::LibXML::import("Spreadsheet::XLSX::Reader::LibXML", "v0.38.2") called at -e line 0
        main::BEGIN() called at -e line 0
        eval {...} called at -e line 0
BEGIN failed--compilation aborted.
```

This means that people cannot set a minimum required version using the default syntax rules. If selection based on version is required, you are now forcing users to "use version" and qv.

**Comment by Tux** [comment]
as an important side-note: version was only in core as of perl-5.10
that means that if I want to correctly support your versioning system from Spreadsheet::Read, which requires 5.006, I have to add a dependency, which I will not do.

**Comment by jandrew** [comment]
Let me look into this.  I'm just finishing up the last set of issues to release and updating the documentation.  I like 'version' for several reasons that I seem to hold in the minority but I don't feel tied to it.  Let me explore some options and see if I can manage this a bit better.

**Comment by jandrew** [comment]
It looks like this is an artifact of the logic in my import statement so I will fix it there.  The test implementation is to confess the following.

"Version -$required_version- required - the installed version is: $VERSION"
