### ISSUE TITLE
fails with Spreadsheet::Read with perl-5.10.1

### ISSUE THREAD

**Issue by Tux** [jandrew/Spreadsheet-XLSX-Reader-LibXML#72]
https://rt.cpan.org/Ticket/Display.html?id=107135

I can reproduce that when I install the huge list of prereqs on 5.10.1
For now I think it is safe to just disable this parser for S::R with all perl versions older than 5.12.0 (which is what I just committed and pushed).

You have two choices here:
1. require 5.12.0 or newer for your module and be done with it
2. Install the complete 5.10.1 tree with prereqs and fix the failures

If you choose 2 and all works, I'll re-enable your parser for 5.10.1 again in S::R

**Comment by jandrew** [comment]
Thanks for reporting this.  As a minimum for the next release to github I will specifically add 5.10.1 testing for TravisCI.  I want to see if I can track down what is happening and fix it if I can.

**Comment by jandrew** [comment]
My understanding is that there is an upcoming announcement on CPAN testers that should improve things but I have also been sad that the servers have been intermittent.

**Comment by jandrew** [comment]
So I rolled a potential fix for the last error from Slavin Rezić

    Use of uninitialized value $trailinq_zeros in length at /opt/perl-5.10.1/lib/site_perl/5.10.1/Spreadsheet/XLSX/Reader/LibXML/ParseExcelFormatStrings.pm line 799.

I have also added perl 5.10.1 testing to my TravisCI tests.

 I will run TravisCI at 5.10.1 and see if I can catch the failures and then re-run with the fix and see if it goes away.

I confirmed the fail with TravisCI at

https://travis-ci.org/jandrew/Spreadsheet-XLSX-Reader-LibXML/jobs/81123745

**Comment by jandrew** [comment]
OK,  Now I have passes with 5.10.1 and no warnings

https://travis-ci.org/jandrew/Spreadsheet-XLSX-Reader-LibXML/builds/81126454

https://travis-ci.org/jandrew/Spreadsheet-XLSX-Reader-LibXML/jobs/81126456

https://travis-ci.org/jandrew/Spreadsheet-XLSX-Reader-LibXML/builds/81126465

https://travis-ci.org/jandrew/Spreadsheet-XLSX-Reader-LibXML/jobs/81126467

I still have to update the documentation but then I will release

**Comment by jandrew** [comment]
Closed with release of v0.38.16
