### ISSUE TITLE
depends on older version of itself

### ISSUE THREAD

**Issue by chorny** [jandrew/Spreadsheet-XLSX-Reader-LibXML#99]
Spreadsheet::XLSX::Reader::LibXML::XMLReader::CalcChain is in version 0.38.22

**Comment by jandrew** [comment]
I can fix that.  Thanks for the notification

**Comment by jandrew** [comment]
It looks like Spreadsheet::XLSX::Reader::LibXML::XMLReader::Styles and Spreadsheet::XLSX::Reader::LibXML::XMLReader::SharedStrings are also old and still required too.
